{% set name = "ropgadget" %}
{% set version = "7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ROPGadget-{{ version }}.tar.gz
  sha256: 4078e70601a2dc869123dfa352812dcc44767a4bbde482b7059d34b33bb67850

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - capstone >=5.0.0rc2

test:
  imports:
    - ropgadget
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JonathanSalwan/ROPgadget
  summary: This tool lets you search your gadgets on your binaries to facilitate your ROP exploitation.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
