{% set name = "ropgadget" %}
{% set version = "6.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ROPGadget-{{ version }}.tar.gz
  sha256: 8ce1164d64cb524e07bb67b8e03e57eea1535432b712de9b7efc98829de8ea05

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - capstone
    - python

test:
  imports:
    - ropgadget
    - ropgadget.loaders
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JonathanSalwan/ROPgadget
  summary: This tool lets you search your gadgets on your binaries to facilitate your ROP exploitation.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
